# Generated by Django 4.2.23 on 2025-07-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = []
