# Generated by Django 4.2.23 on 2025-07-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0013_fix_sqlite_compatibility"),
    ]

    operations = []
