# Generated by Django 4.2.23 on 2025-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0012_add_notification_read_at"),
        ("monitoring", "0014_complete_sqlite_fix"),
    ]

    operations = []
