# Generated by Django 4.2.23 on 2025-07-04 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monitoring", "0015_merge_20250701_2020"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Créée"),
                            ("acknowledged", "Prise en compte"),
                            ("resolved", "Résolue"),
                            ("closed", "Fermée"),
                            ("reopened", "Rouverte"),
                            ("status_changed", "Statut modifié"),
                            ("severity_changed", "Sévérité modifiée"),
                            ("comment_added", "Commentaire ajouté"),
                            ("false_positive", "Marquée faux positif"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ancienne valeur"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Nouvelle valeur"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Horodatage"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="monitoring.alert",
                        verbose_name="Alerte",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'alerte",
                "verbose_name_plural": "Historiques d'alerte",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["alert"], name="monitoring__alert_i_7900c6_idx"
                    ),
                    models.Index(
                        fields=["user"], name="monitoring__user_id_01f184_idx"
                    ),
                    models.Index(
                        fields=["action"], name="monitoring__action_85f844_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_82f87a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Commentaire")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="Commentaire interne"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="monitoring.alert",
                        verbose_name="Alerte",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire d'alerte",
                "verbose_name_plural": "Commentaires d'alerte",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["alert"], name="monitoring__alert_i_b8e3f0_idx"
                    ),
                    models.Index(
                        fields=["user"], name="monitoring__user_id_933208_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="monitoring__created_68067c_idx"
                    ),
                ],
            },
        ),
    ]
