services:
  traffic-control:
    image: python:3.10-slim
    container_name: nms-traffic-control
    restart: unless-stopped
    privileged: true
    networks:
      - nms-backend
    ports:
      - "8003:8003"
    volumes:
      - ./services/traffic-control:/app
      - ./config/tc:/etc/tc
    working_dir: /app
    environment:
      - REDIS_HOST=nms-redis
      - REDIS_PORT=6379
    command: >
      bash -c "apt-get update && apt-get install -y iproute2 iptables net-tools ethtool curl procps && 
      pip install -r requirements.txt && 
      python app.py"

networks:
  nms-backend:
    external: true
    name: network-management-system_nms-backend
