# Generated by Django 4.2.23 on 2025-06-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0006_fix_aimodel_schema"),
    ]

    operations = []
