# Generated by Django 4.2.23 on 2025-06-28 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0007_sync_database_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="question",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
