# Generated by Django 4.2.23 on 2025-07-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_assistant", "0008_alter_message_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                            ("de", "Deutsch"),
                        ],
                        default="fr",
                        max_length=10,
                    ),
                ),
                (
                    "response_style",
                    models.CharField(
                        choices=[
                            ("concise", "Concise"),
                            ("detailed", "Detailed"),
                            ("technical", "Technical"),
                            ("friendly", "Friendly"),
                        ],
                        default="detailed",
                        max_length=20,
                    ),
                ),
                ("max_conversation_length", models.IntegerField(default=100)),
                ("enable_notifications", models.BooleanField(default=True)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("enable_command_execution", models.BooleanField(default=False)),
                ("enable_file_analysis", models.BooleanField(default=True)),
                ("enable_code_generation", models.BooleanField(default=True)),
                ("enable_network_analysis", models.BooleanField(default=True)),
                (
                    "require_confirmation_for_commands",
                    models.BooleanField(default=True),
                ),
                ("allowed_command_categories", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.aimodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "ai_assistant_userpreference",
            },
        ),
    ]
