# Generated by Django 4.2.23 on 2025-06-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompliancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type d'équipement"
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fabricant"
                    ),
                ),
                ("rules", models.JSONField(verbose_name="Règles")),
                (
                    "severity",
                    models.CharField(
                        default="medium", max_length=50, verbose_name="Sévérité"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Créé par"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Politique de conformité",
                "verbose_name_plural": "Politiques de conformité",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "device_type",
                    models.CharField(max_length=50, verbose_name="Type d'équipement"),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fabricant"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Version OS"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(blank=True, null=True, verbose_name="Variables"),
                ),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="Tags")),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Créé par"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de configuration",
                "verbose_name_plural": "Modèles de configuration",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(max_length=50, verbose_name="Type d'équipement"),
                ),
                ("vendor", models.CharField(max_length=100, verbose_name="Fabricant")),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Modèle"),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Version OS"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de série"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Emplacement"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        default="unknown", max_length=50, verbose_name="Statut"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données supplémentaires"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipement réseau",
                "verbose_name_plural": "Équipements réseau",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "layout",
                    models.JSONField(blank=True, null=True, verbose_name="Disposition"),
                ),
                (
                    "devices",
                    models.JSONField(blank=True, null=True, verbose_name="Équipements"),
                ),
                (
                    "connections",
                    models.JSONField(blank=True, null=True, verbose_name="Connexions"),
                ),
                (
                    "is_auto_discovered",
                    models.BooleanField(
                        default=False, verbose_name="Découverte automatique"
                    ),
                ),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="Tags")),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Créé par"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Topologie",
                "verbose_name_plural": "Topologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NetworkInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="Adresse MAC"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "subnet_mask",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Masque de sous-réseau"
                    ),
                ),
                (
                    "interface_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type d'interface"
                    ),
                ),
                (
                    "speed",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Vitesse (bps)"
                    ),
                ),
                ("mtu", models.IntegerField(blank=True, null=True, verbose_name="MTU")),
                (
                    "status",
                    models.CharField(
                        default="unknown", max_length=50, verbose_name="Statut"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données supplémentaires"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="network_management.networkdevice",
                        verbose_name="Équipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interface réseau",
                "verbose_name_plural": "Interfaces réseau",
                "ordering": ["device", "name"],
                "unique_together": {("device", "name")},
            },
        ),
        migrations.CreateModel(
            name="DeviceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "version",
                    models.CharField(
                        default="running", max_length=50, verbose_name="Version"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "status",
                    models.CharField(
                        default="draft", max_length=50, verbose_name="Statut"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Créé par"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'application"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Erreur")),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données supplémentaires"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="network_management.networkdevice",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="network_management.deviceconfiguration",
                        verbose_name="Configuration parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration d'équipement",
                "verbose_name_plural": "Configurations d'équipements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_compliant", models.BooleanField(verbose_name="Conforme")),
                ("results", models.JSONField(verbose_name="Résultats")),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "checked_by",
                    models.CharField(max_length=255, verbose_name="Vérifié par"),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_checks",
                        to="network_management.deviceconfiguration",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_checks",
                        to="network_management.networkdevice",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_checks",
                        to="network_management.compliancepolicy",
                        verbose_name="Politique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification de conformité",
                "verbose_name_plural": "Vérifications de conformité",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "severity",
                    models.CharField(
                        default="medium", max_length=50, verbose_name="Sévérité"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=50, verbose_name="Statut"
                    ),
                ),
                ("source", models.CharField(max_length=100, verbose_name="Source")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Catégorie"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Détails"),
                ),
                (
                    "acknowledged",
                    models.BooleanField(default=False, verbose_name="Acquittée"),
                ),
                (
                    "acknowledged_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Acquittée par"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'acquittement"
                    ),
                ),
                (
                    "acknowledgement_comment",
                    models.TextField(
                        blank=True, verbose_name="Commentaire d'acquittement"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_alerts",
                        to="network_management.networkdevice",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="network_management.networkinterface",
                        verbose_name="Interface",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        default="ethernet",
                        max_length=50,
                        verbose_name="Type de connexion",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="unknown", max_length=50, verbose_name="Statut"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données supplémentaires"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "source_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_connections",
                        to="network_management.networkdevice",
                        verbose_name="Équipement source",
                    ),
                ),
                (
                    "source_interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_connections",
                        to="network_management.networkinterface",
                        verbose_name="Interface source",
                    ),
                ),
                (
                    "target_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_connections",
                        to="network_management.networkdevice",
                        verbose_name="Équipement cible",
                    ),
                ),
                (
                    "target_interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_connections",
                        to="network_management.networkinterface",
                        verbose_name="Interface cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connexion réseau",
                "verbose_name_plural": "Connexions réseau",
                "ordering": ["source_device", "source_interface"],
                "unique_together": {("source_interface", "target_interface")},
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("value", models.FloatField(verbose_name="Valeur")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Unité"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Catégorie"),
                ),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="Tags")),
                ("timestamp", models.DateTimeField(verbose_name="Horodatage")),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_metrics",
                        to="network_management.networkdevice",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_metrics",
                        to="network_management.networkinterface",
                        verbose_name="Interface",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrique",
                "verbose_name_plural": "Métriques",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "name", "timestamp"],
                        name="network_man_device__2c8f8d_idx",
                    ),
                    models.Index(
                        fields=["interface", "name", "timestamp"],
                        name="network_man_interfa_778c8b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50, verbose_name="Niveau")),
                ("message", models.TextField(verbose_name="Message")),
                ("source", models.CharField(max_length=100, verbose_name="Source")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Détails"),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Horodatage")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'enregistrement"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="network_management.networkdevice",
                        verbose_name="Équipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "level", "timestamp"],
                        name="network_man_device__7ae571_idx",
                    ),
                    models.Index(
                        fields=["source", "timestamp"],
                        name="network_man_source_27c6f0_idx",
                    ),
                ],
            },
        ),
    ]
