# Generated by Django 4.2.23 on 2025-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='vendor',
            field=models.CharField(max_length=100, verbose_name="Fabricant", default='Unknown'),
            preserve_default=False,
        ),
    ]
