# Generated by Django 4.2.23 on 2025-06-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network_management", "0002_auto_20250623_1846"),
    ]

    operations = [
        # Marquer cette migration comme appliquée sans rien faire
        # car la base de données est déjà dans l'état souhaité
    ]
