# Generated by Django 4.2.23 on 2025-06-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network_management", "0003_remove_networkdevice_contact_and_more"),
    ]

    operations = [
        # Cette migration marque les changements déjà appliqués manuellement en SQL
        # Les modifications suivantes ont été appliquées directement en base :
        # - Ajout de parent_id (ForeignKey vers self)
        # - Ajout de content (TextField)
        # - Suppression de name, description, file
        
        # Migration factice - les changements sont déjà en base
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;",
        ),
    ]
