# Generated by Django 4.2.23 on 2025-06-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("network_management", "0004_update_deviceconfiguration_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkdevice",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="networkdevice",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="networkdevice",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="networkdevice",
            name="status",
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="credentials",
            field=models.JSONField(blank=True, null=True, verbose_name="Identifiants"),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="discovery_method",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Méthode de découverte"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="hostname",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom d'hôte"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="is_virtual",
            field=models.BooleanField(default=False, verbose_name="Virtuel"),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="last_discovered",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière découverte"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="last_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière synchronisation"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="mac_address",
            field=models.CharField(
                blank=True, max_length=17, verbose_name="Adresse MAC"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="management_interface",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Interface de gestion"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Fabricant"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Métadonnées"),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="node_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID de nœud"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="os",
            field=models.CharField(blank=True, max_length=100, verbose_name="OS"),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="snmp_community",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Communauté SNMP"
            ),
        ),
        migrations.AlterField(
            model_name="networkdevice",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="Adresse IP"),
        ),
        migrations.AlterField(
            model_name="networkdevice",
            name="vendor",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Fabricant"
            ),
        ),
    ]
