# Generated by Django 4.2.23 on 2025-06-30 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("network_management", "0009_create_log_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        max_length=100, verbose_name="Type de tableau de bord"
                    ),
                ),
                ("configuration", models.JSONField(verbose_name="Configuration")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Par défaut"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de tableau de bord",
                "verbose_name_plural": "Configurations de tableaux de bord",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="log",
            new_name="network_man_device__7ae571_idx",
            old_name="network_man_device_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="log",
            new_name="network_man_source_27c6f0_idx",
            old_name="network_man_source_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="metric",
            new_name="network_man_device__2c8f8d_idx",
            old_name="network_man_device_b8e8e8_idx",
        ),
        migrations.RenameIndex(
            model_name="metric",
            new_name="network_man_interfa_778c8b_idx",
            old_name="network_man_interfa_a1b2c3_idx",
        ),
        migrations.AddField(
            model_name="dashboardconfiguration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_configurations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardconfiguration",
            unique_together={("dashboard_type", "user")},
        ),
    ]
