# Generated by Django 4.2.23 on 2025-07-04 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("network_management", "0010_dashboardconfiguration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkTopology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de la topologie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "topology_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physique"),
                            ("logical", "Logique"),
                            ("gns3_imported", "Importé de GNS3"),
                            ("custom", "Personnalisé"),
                        ],
                        default="physical",
                        max_length=50,
                        verbose_name="Type de topologie",
                    ),
                ),
                (
                    "gns3_project_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID Projet GNS3"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "topology_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données de topologie"
                    ),
                ),
                (
                    "layout_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données de mise en page"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="topologies",
                        to="network_management.networkdevice",
                        verbose_name="Équipements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topologie réseau",
                "verbose_name_plural": "Topologies réseau",
                "ordering": ["-updated_at"],
            },
        ),
    ]
