# Generated by Django 4.2.23 on 2025-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indique si le widget est actif",
                verbose_name="Actif",
            ),
        ),
    ]
