# Generated by Django 4.2.23 on 2025-07-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security_management", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE security_management_securityalert RENAME TO security_management_securityalertmodel;",
            reverse_sql="ALTER TABLE security_management_securityalertmodel RENAME TO security_management_securityalert;"
        ),
    ]
