# Generated by Django 4.2.23 on 2025-07-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("security_management", "0003_auto_20250713_0043"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoReportAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("included_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuricataAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("signature", models.TextField()),
                ("category", models.CharField(default="Unknown", max_length=255)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                        ],
                        default=3,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("source_port", models.IntegerField(default=0)),
                ("destination_port", models.IntegerField(default=0)),
                ("protocol", models.CharField(default="", max_length=10)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("auto_report_triggered", models.BooleanField(default=False)),
                (
                    "auto_report_session_id",
                    models.CharField(blank=True, max_length=100),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="security_ma_timesta_09d20e_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "destination_ip"],
                        name="security_ma_source__b481dc_idx",
                    ),
                    models.Index(
                        fields=["processed", "timestamp"],
                        name="security_ma_process_49c62d_idx",
                    ),
                    models.Index(
                        fields=["auto_report_triggered", "timestamp"],
                        name="security_ma_auto_re_d48165_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityMonitoringMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("scan_duration_seconds", models.FloatField(default=0.0)),
                ("alerts_scanned", models.IntegerField(default=0)),
                ("new_alerts_found", models.IntegerField(default=0)),
                ("critical_alerts", models.IntegerField(default=0)),
                ("high_alerts", models.IntegerField(default=0)),
                ("medium_alerts", models.IntegerField(default=0)),
                ("low_alerts", models.IntegerField(default=0)),
                ("reports_triggered", models.IntegerField(default=0)),
                ("notifications_sent", models.IntegerField(default=0)),
                ("elasticsearch_available", models.BooleanField(default=False)),
                ("suricata_running", models.BooleanField(default=False)),
                ("celery_worker_available", models.BooleanField(default=False)),
                ("scan_errors", models.JSONField(default=list)),
                ("average_response_time", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-scan_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["scan_timestamp"], name="security_ma_scan_ti_f1fa7c_idx"
                    ),
                    models.Index(
                        fields=["new_alerts_found", "scan_timestamp"],
                        name="security_ma_new_ale_7f674d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutoSecurityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatique"),
                            ("scheduled", "Planifié"),
                            ("manual", "Manuel"),
                            ("incident", "Incident"),
                            ("real_time", "Temps réel"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("generating", "En cours de génération"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("sent", "Envoyé"),
                            ("notification_sent", "Notifications envoyées"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("total_alerts", models.IntegerField(default=0)),
                ("critical_alerts", models.IntegerField(default=0)),
                ("high_alerts", models.IntegerField(default=0)),
                ("medium_alerts", models.IntegerField(default=0)),
                ("low_alerts", models.IntegerField(default=0)),
                ("detection_rate", models.FloatField(default=100.0)),
                ("response_time_minutes", models.FloatField(default=0.0)),
                ("report_file_path", models.CharField(blank=True, max_length=500)),
                ("report_file_size", models.BigIntegerField(default=0)),
                ("email_sent", models.BooleanField(default=False)),
                ("telegram_sent", models.BooleanField(default=False)),
                ("notification_details", models.JSONField(default=dict)),
                (
                    "trigger_source",
                    models.CharField(default="automatic_monitoring", max_length=100),
                ),
                ("trigger_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("generation_task_id", models.CharField(blank=True, max_length=100)),
                ("notification_task_id", models.CharField(blank=True, max_length=100)),
                (
                    "included_alerts",
                    models.ManyToManyField(
                        related_name="auto_reports",
                        through="security_management.AutoReportAlert",
                        to="security_management.suricataalert",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="autoreportalert",
            name="alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="security_management.suricataalert",
            ),
        ),
        migrations.AddField(
            model_name="autoreportalert",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="security_management.autosecurityreport",
            ),
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("intrusion_detection", "Détection d'intrusion"),
                            ("malware_detection", "Détection de malware"),
                            ("suspicious_activity", "Activité suspecte"),
                            ("policy_violation", "Violation de politique"),
                            ("authentication_failure", "Échec d'authentification"),
                            ("privilege_escalation", "Escalade de privilèges"),
                            ("data_exfiltration", "Exfiltration de données"),
                            ("ddos_attack", "Attaque DDoS"),
                            ("brute_force", "Attaque par force brute"),
                            ("sql_injection", "Injection SQL"),
                            ("xss_attack", "Attaque XSS"),
                            ("automatic_detection", "Détection automatique"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critique"),
                            ("high", "Élevée"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                            ("info", "Information"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("destination_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("source_port", models.IntegerField(blank=True, null=True)),
                ("destination_port", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("event_data", models.JSONField(default=dict)),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to="security_management.suricataalert",
                    ),
                ),
                (
                    "related_security_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correlated_events",
                        to="security_management.securityalertmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["detected_at", "severity"],
                        name="security_ma_detecte_d19528_idx",
                    ),
                    models.Index(
                        fields=["event_type", "severity"],
                        name="security_ma_event_t_54390c_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "destination_ip"],
                        name="security_ma_source__8fa9e0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="autosecurityreport",
            index=models.Index(
                fields=["created_at", "status"], name="security_ma_created_e7597d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autosecurityreport",
            index=models.Index(
                fields=["report_type", "status"], name="security_ma_report__de7c55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autosecurityreport",
            index=models.Index(
                fields=["session_id", "status"], name="security_ma_session_b8fbdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autoreportalert",
            index=models.Index(
                fields=["report", "included_at"], name="security_ma_report__e21847_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="autoreportalert",
            unique_together={("report", "alert")},
        ),
    ]
